// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSSZwhCU5PIP2kabRzzQYvWqtD_k4gghc',
    appId: '1:589144795862:web:52bc60a9e092d56dad7777',
    messagingSenderId: '589144795862',
    projectId: 'book-worm-4dd5a',
    authDomain: 'book-worm-4dd5a.firebaseapp.com',
    storageBucket: 'book-worm-4dd5a.appspot.com',
    measurementId: 'G-LWR4LC0LM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLeELJ5If4-rN67e7juv8NrHpmVX3FFVE',
    appId: '1:589144795862:android:eb1c9f57f3dd0eb7ad7777',
    messagingSenderId: '589144795862',
    projectId: 'book-worm-4dd5a',
    storageBucket: 'book-worm-4dd5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDab8LxMyI7KTn8q6jaBnUWGRnb1PPhDQs',
    appId: '1:589144795862:ios:32693fc760ddfe5aad7777',
    messagingSenderId: '589144795862',
    projectId: 'book-worm-4dd5a',
    storageBucket: 'book-worm-4dd5a.appspot.com',
    iosBundleId: 'com.example.bookWorm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDab8LxMyI7KTn8q6jaBnUWGRnb1PPhDQs',
    appId: '1:589144795862:ios:a33907c76251447aad7777',
    messagingSenderId: '589144795862',
    projectId: 'book-worm-4dd5a',
    storageBucket: 'book-worm-4dd5a.appspot.com',
    iosBundleId: 'com.example.bookWorm.RunnerTests',
  );
}
